# Generated by Django 5.1.6 on 2025-02-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalProfessor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notas',
            old_name='aluno_id',
            new_name='aluno',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='disciplina_id',
            new_name='disciplina',
        ),
    ]
