# Generated by Django 5.1.6 on 2025-02-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalProfessor', '0002_rename_aluno_id_notas_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='serie',
            field=models.CharField(choices=[('1', '1º Ano'), ('2', '2º Ano'), ('3', '3º Ano')], max_length=200),
        ),
    ]
