# Generated by Django 5.1.6 on 2025-02-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalProfessor', '0003_alter_alunos_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='matricula',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
