# Generated by Django 5.1.6 on 2025-02-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalProfessor', '0004_alter_alunos_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil_aluno'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil_professor'),
        ),
    ]
