# Generated by Django 5.1.6 on 2025-02-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalProfessor', '0005_alunos_foto_perfil_usuarios_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='fotos_perfil_aluno/semFoto.jpg', null=True, upload_to='fotos_perfil_aluno'),
        ),
    ]
