# Generated by Django 5.1.6 on 2025-02-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalProfessor', '0007_alter_usuarios_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='fotos_perfil_professor/semFoto.jpg', upload_to='fotos_perfil_professor'),
        ),
    ]
