# Generated by Django 5.1.6 on 2025-02-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalProfessor', '0009_alter_alunos_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='notaExtra',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
