# Generated by Django 5.1.6 on 2025-02-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalProfessor', '0011_remove_alunos_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultado_aluno_approved_disciplinas',
            old_name='aluno_id',
            new_name='aluno',
        ),
        migrations.RenameField(
            model_name='resultado_aluno_approved_disciplinas',
            old_name='disciplina_id',
            new_name='disciplina',
        ),
    ]
